databases:
  - name: gatekeeperdb
    plan: free
    databaseName: gatekeeper
    user: user_auth_sys

services:
  - type: web
    plan: free
    name: user_auth_sys
    env: python
    rootDir: user_auth_sys
    buildCommand: './build.sh'
    startCommand: 'gunicorn user_auth_sys.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gatekeeperdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: EMAIL_HOST_USER
        value: cybercodemomo@gmail.com
      - key: EMAIL_HOST_PASSWORD
        value: xawndgtjoajcrvtr
      - key: EMAIL_HOST
        value: smtp.gmail.com   # or your SMTP host
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USE_TLS
        value: "True"