# Generated by Django 5.2.4 on 2025-07-16 10:18

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('gender', models.CharField(blank=True, choices=[('male', 'MALE'), ('female', 'FEMALE')], max_length=6, verbose_name='User Gender')),
                ('bio', models.TextField(blank=True, max_length=250)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='NG')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birth Date')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='User Location')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Profile',
                'verbose_name_plural': 'Data Profiles',
            },
        ),
    ]
