# Generated by Django 5.2.4 on 2025-07-26 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profiledata_age_alter_profiledata_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledata',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'MALE'), ('female', 'FEMALE'), ('other', 'OTHER')], default='male', max_length=6, verbose_name='User Gender'),
        ),
    ]
