# Generated by Django 5.2.4 on 2025-08-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_profiledata_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledata',
            name='image',
            field=models.ImageField(blank=True, default='profile_images/default.jpg', null=True, upload_to='profile_images/'),
        ),
    ]
