# Generated by Django 5.2.4 on 2025-08-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_profiledata_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledata',
            name='bio',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='profiledata',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='User Location'),
        ),
    ]
